" Conditional plugin excludes
let g:pathogen_disabled = []
if !has('python3')
	call extend(g:pathogen_disabled, ['vimsence', 'YouCompleteMe'])
endif
if has('win32') || has('win64')
	call extend(g:pathogen_disabled, ['cursorword'])
endif

execute pathogen#infect()

" Load ./ftplugin/*, ./indent/* and tries to detect filetype
" cf. https://vi.stackexchange.com/a/10125
filetype plugin indent on

" Change viminfo path (stop poluting my home folder!!)
set viminfo+=n~/.vim/viminfo

" Enable modelines
" cf. http://vim.wikia.com/wiki/Modeline_magic
set modeline
set modelines=5

" Persistent undo
set undofile
set undodir='~/.vim/undo'
set undolevels=1000
set undoreload=10000

" Indentation set to use smart tabs
" cf. http://vim.wikia.com/wiki/Indent_with_tabs,_align_with_spaces
set noexpandtab
set copyindent
set preserveindent
set softtabstop=0
set shiftwidth=8
set tabstop=8

set mouse=a

set relativenumber
set number
set numberwidth=1

syntax on
let g:molokai_original=1
colorscheme molokai
hi Normal      ctermbg=0
hi ColorColumn ctermbg=1
hi LineNr      ctermfg=8
hi LineNr      ctermbg=0
hi Visual      ctermbg=8
