#!/usr/bin/env bash

print_info() {
    info title 
    info underline 

    info "OS" distro 
    info "Host" model
    info "Kernel" kernel
#    info "Uptime" uptime
    info "Shell" shell
    info "Resolution" resolution
    info "DE" de
    info "WM" wm
    info "Terminal" term
    info "Terminal Font" term_font
    info "CPU" cpu
    info "GPU" gpu
#	info "Memory" memory
#	info "GPU Driver" gpu_driver # Linux only
#	info "Disk" disk
#	info "Install Date" install_date
#	info "Locale" locale # This only works on glibc systems.

    info line_break 
    info cols 
    info line_break 
}

kernel_shorthand="off"
distro_shorthand="on"
os_arch="on"
uptime_shorthand="on"
shell_path="off"
shell_version="on"
speed_type="bios_limit"
speed_shorthand="on"
cpu_brand="on"
cpu_speed="on"
cpu_cores="logical"
cpu_temp="off"
gpu_brand="on"
gpu_type="all"
refresh_rate="on"
gtk_shorthand="off"
gtk2="on"
gtk3="on"
public_ip_host="http://ident.me"
disk_show=('/')
disk_subtitle="dir"
song_shorthand="off"
install_time="on"
install_time_format="12h"
colors=(distro)

bold="on"

underline_enabled="on"
underline_char="-"

block_range=(0 15)
color_blocks="on"
block_width=3
block_height=1

bar_char_elapsed="-"
bar_char_total="="
bar_border="on"
bar_length=15
bar_color_elapsed="distro"
bar_color_total="distro"

cpu_display="off"
memory_display="off"
battery_display="off"
disk_display="off"

image_backend="ascii"
image_source="$HOME/.config/neofetch/image.png"
ascii_distro="auto"
ascii_colors=(distro)
ascii_bold="on"
image_loop="on"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
crop_mode="normal"
crop_offset="center"
image_size="auto"

gap=3
yoffset=0
xoffset=0

background_color=

scrot="off"
crot_cmd="auto"
scrot_name="neofetch-$(date +%F-%I-%M-%S-${RANDOM}).png"
image_host="teknik"
stdout="off"

config_version="3.3.0"
