#!/bin/zsh
###############
# ZSH OPTIONS #
###############

zstyle :compinstall filename "$cfg"'/zsh/zshrc'

autoload -Uz compinit
rm -f "$HOME"'/.zcompdump'; compinit -d "$cfg"'/zsh/zcompdump'

zstyle ':completion:*' menu select
