#!/bin/zsh
###############
# ZSH OPTIONS #
###############

# zstyle :compinstall filename "$cfg"'/zsh/zshrc'

# Case insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

autoload -U +X bashcompinit && bashcompinit
autoload -Uz compinit
compinit

# yes is needed for ssh completion
zstyle ':completion:*' menu yes select

setopt inc_append_history

unsetopt correct_all

# Allow commands in PS1
setopt PROMPT_SUBST
