#!/bin/zsh
###############
# ZSH OPTIONS #
###############

zstyle :compinstall filename "$cfg"'/zsh/zshrc'

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
autoload -Uz compinit
rm -f "$HOME"'/.zcompdump'; compinit -d "$cfg"'/zsh/zcompdump'

zstyle ':completion:*' menu select

setopt appendhistory

unsetopt correct_all
