#!/bin/zsh
##############
# ZSH PROMPT #
##############

precmd() {
	curpath="%F{green}%~%f"
	user="%F{cyan}%n%f"
	host="%F{blue}${HOSTNAME_DISPLAY:-%m}%f"
	char="%f%# "

	export PS1="%f"
    if [ -f "$KUBECONFIG" ]; then
		kubectx=$(grep 'current-context:' "$KUBECONFIG" | awk '{print $2}')
		if [[ -n "$kubectx" && $kubectx != '""' ]]; then
			if [[ "$kubectx" == *"/"* ]]; then
				kubectx=${kubectx##*/}
			fi
			PS1+="%F{yellow}(kube: $kubectx)%f "
		fi
	fi

	PS1+=$'\n'"[%f$user@%f$host]%f$char%f"

	export RPROMPT="$curpath"
}