#!/bin/zsh
##############
# ZSH PROMPT #
##############

precmd() {
	curpath="%F{green}%~%f"
	user="%F{cyan}%n%f"
	host="%F{blue}${HOSTNAME_DISPLAY:-%m}%f"
	char="%f%# "

	export PS1="%f"
	KUBECONFIG="${KUBECONFIG:-"$HOME/.kube/config"}"
    if [ -f "$KUBECONFIG" ]; then
		kubectx=$(grep 'current-context:' "$KUBECONFIG" | awk '{print $2}')
		if [[ -n "$kubectx" && $kubectx != '""' ]]; then
			if [[ "$kubectx" == *"/"* ]]; then
				kubectx=${kubectx##*/}
			fi
			PS1+="%F{cyan}(kube: $kubectx)%f "
		fi
	fi
	if [ -n "$VIRTUAL_ENV" ]; then
		venv_name=$(basename "$(dirname "$VIRTUAL_ENV")")
		PS1+="%F{green}(venv: $venv_name)%f "
	fi
	if [ -n "$AWS_PROFILE" ]; then
		PS1+="%F{yellow}(aws: $AWS_PROFILE)%f "
	fi

	PS1+=$'\n'"[%f$user@%f$host]%f$char%f"

	export RPROMPT="$curpath"
}