include () {
	if [ -f "$1" ]; then
		if [ -n "$DEBUG_START" ]; then
			date '+%M:%S.%N'
			echo $file
		fi
 	       source "$1"
	fi
}

cfg="$HOME"'/.config'

init_files=(
	"$cfg"'/bash/functions'
	"$cfg"'/bash/environment'
	"$cfg"'/bash/aliases'
	"$cfg"'/zsh/prompt'
	"$cfg"'/zsh/bindings'
	"$cfg"'/zsh/options'
	"$cfg"'/zsh/custom'
	"$cfg"'/bash/completion'
	"$HOME"'/.fzf.zsh'
	"$HOME"'/.opam/opam-init/init/init.zsh'
	'/usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
	'/usr/share/doc/fzf/examples/completion.zsh'
	'/usr/share/doc/fzf/examples/key-bindings.zsh'
	'/usr/share/fzf/key-bindings.zsh'
	'/usr/share/fzf/shell/key-bindings.zsh'
	'/usr/local/share/fzf/key-bindings.zsh'
	'/usr/local/share/fzf/shell/key-bindings.zsh'
	'/opt/homebrew/opt/fzf/shell/completion.zsh'
	'/opt/homebrew/opt/fzf/shell/key-bindings.zsh'
	'/usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
	'/opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
	'/usr/share/zsh/site-functions/fzf'
	/data/data/com.termux/files/usr/share/fzf/completion.zsh
	/data/data/com.termux/files/usr/share/fzf/key-bindings.zsh
	/etc/profile.d/vte.sh
	'/opt/homebrew/opt/nvm/nvm.sh'
	'/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm'
	"$cfg"'/bash/custom'
)


for file in "${init_files[@]}"; do
	include "$file"
done
unset init_files

if [ -d /usr/share/zsh/plugins ]; then
	for d in /usr/share/zsh/plugins/*/; do
		include "$d"/*.plugin.zsh
	done
fi

for d in "$HOME/.config/zsh/plugins/"*/; do
	include "$d"/*.plugin.zsh
done

# Bind ctrl+z to resume (fg)
_zsh_cli_fg() { fg; }
zle -N _zsh_cli_fg
bindkey '^Z' _zsh_cli_fg

# Aliases overrides
alias which='whence -p'

# Environment overrides
export SHELL="$(which zsh)"

unset cfg

if cmd_exists thefuck; then
	eval $(thefuck --alias 2>/dev/null)
fi

if cmd_exists aws_completer; then
	complete -C "$(which aws_completer)" aws
fi

if cmd_exists bw; then
	# bw completion is slow to run, so we cache it
	if [ ! -f /tmp/bw-zsh-completion ]; then
		bw completion --shell zsh > /tmp/bw-zsh-completion
	fi
	source /tmp/bw-zsh-completion
	compdef _bw bw
fi

if [ -f ~/.nvm/alias/default ]; then
	nvm use default --silent
fi
