#!/usr/bin/env sh

neofetch --config $HOME/.config/neofetch/welcome.conf
echo Message of the day:
motd
# echo "NA-NANII? KANSEI DRIFTOO!!
# 
# Deja vu! I've just been in this place before. Higher on the street-
# And I know it's my time to go!
# Calling you, and the search is a mystery. Standing on my feet-
# It's so hard when I try to be me, wooooaaah!!
# Deja vu! I've just been in this time before. Higher on the beat-
# And I know it's a place to go!
# Calling you and the search is a mystery. Standing on my feet-
# It's so hard when I try to be me, yeeeaaah!!
# ----------"

# echo "Blandine
# La femme de ma vie
# Je t'aime
#
# Coeur coeur bague
# Fais-moi l'amour
echo ----------
