#!/bin/bash
##############
# SH ALIASES #
##############


# $SHORTCUTS
alias ch='chmod'
alias cls='clear'
alias flex='clear && neofetch --backend off | lolcat && read'
alias open='xdg-open'
alias v='vim'
alias w='which'

# $OVERRIDES
alias feh='feh --force-aliasing'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias ssh='ssh -t'
alias sudo='sudo '

# $OPTIONS AND ARGUMENTS SHORTCUTS
alias g++='g++ -Wall -Wextra -W -std=c++14'
alias gcc='gcc -Wall -Wextra -W'
alias gd='git diff'
alias gds='git diff --staged'
alias glog='git log --graph --pretty=format:"%Cred%h%Creset - %s %Cgreen(%cr) %C(bold blue)<%an>%C(yellow)%d%Creset" --abbrev-commit '
alias gs='git status -u'
alias l='ls -1'
alias ld64='ld -dynamic-linker /lib64/ld-linux-x86-64.so.2'
alias ll='ls -lh'
alias refresh='source ~/.bashrc'
