#!/bin/bash
##############
# SH ALIASES #
##############

alias flex='clear && pfetch && read'
alias refresh='exec $SHELL'

# $SHORTCUTS
alias ch='chmod'
alias cls='clear'
alias hx='helix'
alias n='nvim'
alias open='xdg-open'
alias v='vim'
alias w='which'

# $OVERRIDES
alias dd='dd status=progress'
alias df='df -h --output=source,fstype,size,used,avail,pcent,target -x tmpfs -x devtmpfs'
alias g++='g++ -Wall -Wextra -W'
alias gcc='gcc -Wall -Wextra -W'
alias grep='grep --color=auto'
alias less='less -r'
alias ls='ls --color=auto'
alias ncdu='ncdu --color off'
alias openvpn='openvpn  --up /usr/share/openvpn/contrib/pull-resolv-conf/client.up --down /usr/share/openvpn/contrib/pull-resolv-conf/client.down'
alias ssh='ssh -t'
alias sudo='sudo '
alias tget='webtorrent download'
alias tree='tree -C'

# $OPTIONS AND ARGUMENTS SHORTCUTS
alias gd='git diff'
alias gds='git diff --staged'
alias glog='git log --graph --pretty=format:"%Cred%h%Creset - %s %Cgreen(%cr) %C(bold blue)<%an>%C(yellow)%d%Creset" --abbrev-commit '
alias gs='git status -u'
alias l='ls -1'
alias ld64='ld -dynamic-linker /lib64/ld-linux-x86-64.so.2'
alias ll='ls -lh'
