#!/bin/bash
##############
# SH ALIASES #
##############


# $SHORTCUTS
alias cls='clear '
alias v='vim '

# $LONG COMMANDS
alias uu='sudo apt-get update && sudo apt-get upgrade '
alias refresh='source ~/.bashrc'

# $GIT
alias glog='git log --graph --pretty=format:"%Cred%h%Creset - %s %Cgreen(%cr) %C(bold blue)<%an>%C(yellow)%d%Creset" --abbrev-commit '
alias gd='git diff '
alias gs='git status '
