include() {
	[ -f "$1" ] && source "$1"
}

cfg="$HOME"'/.config'
init_files=(
	'/etc/skel/.bashrc'
	"$cfg"'/bash/environment'
	"$cfg"'/bash/functions'
	"$cfg"'/bash/prompt'
	"$cfg"'/bash/aliases'
	"$cfg"'/bash/custom'
)
for file in "${init_files[@]}"; do
	include "$file"
done
unset cfg init_files

# Disable history file
unset HISTFILE
