#!/bin/bash
#########################
# ENVIRONMENT VARIABLES #
#########################

pathmunge () { 
	if ! echo $PATH | "$(which egrep)" -q "(^|:)$1($|:)" ; then
		if [ "$2" = "after" ] ; then
			PATH=$PATH:$1
		else
			PATH=$1:$PATH
		fi
	fi
}

pathmunge "$HOME"'/.local/bin'

unset pathmunge

# Page format for man(1)
export MANWIDTH=80
# Avoid creating an history file when using less(1)
export LESSHISTFILE=-
