#!/bin/bash
#########################
# ENVIRONMENT VARIABLES #
#########################

alias egrep >/dev/null && unalias egrep
pathmunge () { 
	if ! echo $PATH | "$(which egrep)" -q "(^|:)$1($|:)" ; then
		if [ "$2" = "after" ] ; then
			PATH=$PATH:$1
		else
			PATH=$1:$PATH
		fi
	fi
}

# Add paths to PATH here
pathmunge "$HOME"'/.local/bin'

unset pathmunge


# USER VARIABLES
# Use lowercase here

export config="$HOME"'/.config'
export vimhome="$config"'/vim'
export editor=vim

## SYSTEM VARIABLES
## Use uppercase here

# Page format for man(1)
export MANWIDTH=80
# Avoid creating an history file when using less(1)
export LESSHISTFILE=-
# Colors for ls(1)
export LS_COLORS="$LS_COLORS"'tw=01;34;40:ow=01;34;40:st=01;34;40:'
