#!/bin/bash
#########################
# ENVIRONMENT VARIABLES #
#########################

alias egrep >/dev/null 2>&1 && unalias egrep
pathmunge () { 
	if ! echo $PATH | "$(which egrep)" -q "(^|:)$1($|:)" ; then
		if [ "$2" = "after" ] ; then
			PATH=$PATH:$1
		else
			PATH=$1:$PATH
		fi
	fi
}

# Add paths to PATH here
pathmunge '/var/lib/snapd/snap/bin'
pathmunge "$HOME"'/.local/share/npm/bin'
pathmunge "$HOME"'/.local/bin'
pathmunge "$HOME"'/Repositories/skielred/Dotfiles-scripts/bin'

unset pathmunge

if ! echo $XDG_DATA_DIRS | "$(which egrep)" -q "(^|:)$HOME/.local/share($|:)"; then
	XDG_DATA_DIRS="$HOME"'/.local/share:'$XDG_DATA_DIRS
fi


# USER VARIABLES
# Use lowercase here

export config="$HOME"'/.config'
export vimhome="$config"'/vim'

## SYSTEM VARIABLES
## Use uppercase here

export EDITOR=vim
# Page format for man(1)
export MANWIDTH=80
# Avoid creating an history file when using less(1)
export LESSHISTFILE=-
# Colors for ls(1)
export LS_COLORS="$LS_COLORS"'tw=01;34;40:ow=01;34;40:st=01;34;40:'

[[ -d "/system/app/" && -d "/system/priv-app" ]] && export ANDROID=1

if [ "$ANDROID" ]; then
	export PREFIX="$(sh -c 'echo $PREFIX')"
fi


settitle()
{
	printf "\033]0;%s\007" "$1"
}

settitle "$TERM"

unset settitle
